import mocha from "eslint-plugin-mocha";
import globals from "globals";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all
});

export default [...compat.extends("eslint:recommended"), {
    plugins: {
        mocha,
    },

    languageOptions: {
        globals: {
            ...globals.node,
            _: true,
            ich: true,
            Formatter: true,
            describe: true,
            before: true,
            beforeEach: true,
            after: true,
            afterEach: true,
            it: true,
        },

        ecmaVersion: 11,
        sourceType: "module",

        parserOptions: {
            ecmaFeatures: {
                experimentalObjectRestSpread: true,
            },
        },
    },

    rules: {
        "mocha/handle-done-callback": 2,
        "mocha/no-global-tests": 2,
        "array-callback-return": 2,
        "consistent-return": 2,
        curly: 2,
        eqeqeq: 2,
        "no-alert": 1,
        "no-caller": 2,
        "no-case-declarations": 2,
        "no-div-regex": 0,
        "no-else-return": 2,

        "no-empty-function": [2, {
            allow: ["functions", "arrowFunctions"],
        }],

        "no-empty-pattern": 2,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-implicit-coercion": 2,
        "no-implicit-globals": 2,
        "no-implied-eval": 2,
        "no-multi-spaces": 2,
        "no-loop-func": 2,
        "no-multi-str": 2,
        "no-native-reassign": 2,
        "no-new-wrappers": 2,
        "no-octal": 2,
        "no-octal-escape": 2,
        "no-param-reassign": 2,
        "no-redeclare": 2,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-self-assign": 2,
        "no-self-compare": 2,
        "no-sequences": 2,
        "no-throw-literal": 2,
        "no-unused-expressions": 2,
        "no-unused-labels": 2,
        "no-useless-concat": 2,
        "no-useless-escape": 2,
        "no-void": 2,
        "no-warning-comments": 2,
        "no-with": 2,
        radix: 2,
        "vars-on-top": 2,
        "wrap-iife": 2,
        yoda: 2,
        "init-declarations": 2,
        "no-catch-shadow": 2,
        "no-delete-var": 2,
        "no-label-var": 2,
        "no-restricted-globals": 2,
        "no-shadow": 2,
        "no-shadow-restricted-names": 2,
        "no-undef": 2,
        "no-undef-init": 0,
        "no-undefined": 0,
        "no-unused-vars": 2,
        "no-use-before-define": 2,
        "callback-return": 2,
        "global-require": 0,
        "handle-callback-err": [2, "^(err|error)$"],
        "no-mixed-requires": 0,
        "no-new-require": 2,
        "no-path-concat": 0,
        "no-process-env": 0,
        "no-process-exit": 0,
        "no-sync": 0,
        "array-bracket-spacing": [2, "never"],
        "block-spacing": 2,
        "brace-style": 2,
        camelcase: 2,
        "comma-spacing": 2,
        "comma-style": 2,
        "computed-property-spacing": 2,
        "consistent-this": [2, "self"],
        "eol-last": 2,
        "func-names": 2,
        "func-style": [2, "declaration"],
        "id-blacklist": 2,
        "id-length": 0,
        "id-match": 0,
        indent: ["error", 2],
        "jsx-quotes": 2,
        "key-spacing": 2,
        "keyword-spacing": 2,
        "linebreak-style": 2,
        "lines-around-comment": 2,
        "max-depth": 2,

        "max-len": [2, {
            code: 140,
            tabWidth: 2,
            ignoreUrls: true,
        }],

        "max-nested-callbacks": 2,
        "max-params": [2, 4],
        "max-statements": [2, 30],
        "max-statements-per-line": 2,
        "new-cap": 2,
        "new-parens": 2,
        "newline-after-var": 0,
        "newline-before-return": 0,
        "newline-per-chained-call": 2,
        "no-array-constructor": 2,
        "no-bitwise": 2,
        "no-continue": 2,
        "no-inline-comments": 2,
        "no-lonely-if": 2,
        "no-mixed-spaces-and-tabs": 2,
        "no-multiple-empty-lines": 2,
        "no-negated-condition": 0,
        "no-nested-ternary": 2,
        "no-new-object": 2,
        "no-plusplus": 0,
        "no-restricted-syntax": 2,
        "no-spaced-func": 2,
        "no-ternary": 0,
        "no-trailing-spaces": 0,
        "no-underscore-dangle": 0,
        "no-unneeded-ternary": 1,
        "no-whitespace-before-property": 2,
        "object-curly-spacing": 2,
        "one-var": [2, "never"],
        "one-var-declaration-per-line": 2,
        "operator-assignment": 2,
        "operator-linebreak": 2,
        "padded-blocks": [2, "never"],
        "quote-props": 0,
        quotes: 2,
        "require-jsdoc": 0,
        semi: [2, "always"],
        "semi-spacing": 2,
        "sort-imports": 0,
        "sort-vars": 0,
        "space-before-blocks": 2,

        "space-before-function-paren": [2, {
            anonymous: "always",
            named: "never",
        }],

        "space-in-parens": 2,
        "space-infix-ops": 2,
        "space-unary-ops": 2,
        "spaced-comment": 2,
        "wrap-regex": 0,
        "arrow-body-style": [2, "always"],
        "arrow-parens": 2,
        "arrow-spacing": 2,
        "constructor-super": 2,
        "generator-star-spacing": 2,
        "no-class-assign": 2,
        "no-confusing-arrow": 2,
        "no-const-assign": 2,
        "no-dupe-class-members": 2,
        "no-duplicate-imports": 2,
        "no-new-symbol": 2,
        "no-restricted-imports": 2,
        "no-this-before-super": 2,
        "no-useless-constructor": 2,
        "no-var": 2,
        "object-shorthand": 2,
        "prefer-arrow-callback": 2,
        "prefer-const": 2,
        "prefer-reflect": 2,
        "prefer-rest-params": 2,
        "prefer-spread": 2,
        "prefer-template": 2,
        "require-yield": 2,
        "template-curly-spacing": 2,
        "yield-star-spacing": 2,
        "no-console": 0,
        "no-debugger": 0,
    },
}];